//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Transactions {
    
    private TransactionsTransaction[] transactionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transaction")]
    public TransactionsTransaction[] Transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransactionsTransaction {
    
    private System.DateTime transactionDateField;
    
    private TransactionsTransactionPaymentDetails paymentDetailsField;
    
    private Status statusField;
    
    private string idField;
    
    /// <remarks/>
    public System.DateTime TransactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    public TransactionsTransactionPaymentDetails PaymentDetails {
        get {
            return this.paymentDetailsField;
        }
        set {
            this.paymentDetailsField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TransactionsTransactionPaymentDetails {
    
    private decimal amountField;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum Status {
    
    /// <remarks/>
    Approved,
    
    /// <remarks/>
    Rejected,
    
    /// <remarks/>
    Done,
}
